
#Island Configuration
[Islands_Settings]
	#The chance at which islands spawn. Lower Values increase the frequency.
	#Default chance is 10.
	#Range: 0 ~ 1000000000
	IslandChance = 10
	#Setting this to true will ONLY generate the spawn island.
	#DO NOT USE `/locate` OR IT WILL CRASH YOUR GAME IN THIS MODE!
	# Default is false.
	SurvivalIslandMode = false
	#The spawn island's biome at which you spawn.
	#MUST MATCH BIOME NAME/CASE IN F3.
	#Modded biomes work too!
	#Default is `minecraft:forest`
	SpawnIslandBiome = "minecraft:forest"
	#Decide whether or not islands have beaches
	#default is true
	Beaches = true
	#The average size of all islands & oceans.
	#Ocean size increases with this too resulting in fewer islands.
	#Each Size increase is exponential.
	#Default is 2
	#Range: 0 ~ 30
	IslandSize = 5

[Ocean_Settings]
	#The size of ocean biomes
	#Each Size increase is exponential.
	#Default is 2
	#Range: 1 ~ 30
	OceanBiomeSize = 4

