
[General]
	#How many ticks it takes for process a recipe in the centrifuge. Default 300.
	#Range: > 20
	centrifugeProcessingTime = 300
	#Use items to change the type of a bee.
	#If false, productive bees can only be obtained through breeding. Default false.
	enableItemConverting = false
	#Bees will create combs instead of raw resource. Combs will need to be processed in a centrifuge. Default true.
	enableCombProduce = true
	#How often should a bee attempt to generate items while in the hive. Default 500.
	#Range: > 20
	itemTickRate = 1500

[Worldgen]
	"enable_productivebees:acacia_wood_nest" = true
	"enable_productivebees:gravel_nest" = true
	"enable_productivebees:glowstone_nest" = true
	"enable_productivebees:end_stone_nest" = true
	"enable_productivebees:jungle_wood_nest" = true
	"enable_productivebees:sugar_cane_nest" = true
	"enable_productivebees:nether_quartz_nest" = true
	"enable_productivebees:coarse_dirt_nest" = true
	"enable_productivebees:stone_nest" = true
	"enable_productivebees:nether_brick_nest" = true
	"enable_productivebees:sand_nest" = true
	"enable_productivebees:obsidian_nest" = true
	"enable_productivebees:slimy_nest" = true
	"enable_productivebees:oak_wood_nest" = true
	"enable_productivebees:spruce_wood_nest" = true
	"enable_productivebees:birch_wood_nest" = true
	"enable_productivebees:dark_oak_wood_nest" = true

[Bees]
	#Range: 0.0 ~ 1.0
	"productivebees:glowing_bee" = 0.85
	#Range: 0.0 ~ 1.0
	spawnUndeadBeesChance = 0.01
	#Range: 0.0 ~ 1.0
	"productivebees:gold_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:copper_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:brass_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:emerald_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:iron_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:redstone_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:invar_bee" = 0.0
	#Range: 0.0 ~ 1.0
	"productivebees:bronze_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:coal_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:tungsten_bee" = 0.0
	#Range: 0.0 ~ 1.0
	"productivebees:titanium_bee" = 0.0
	#Range: 0.0 ~ 1.0
	"productivebees:creeper_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:lead_bee" = 0.0
	#Range: 0.0 ~ 1.0
	"productivebees:radioactive_bee" = 0.0
	#Range: 0.0 ~ 1.0
	"productivebees:magmatic_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:amber_bee" = 0.00
	#Range: 0.0 ~ 1.0
	"minecraft:bee" = 0.25
	#Range: 0.0 ~ 1.0
	"productivebees:lapis_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:steel_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:slimy_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:draconic_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:osmium_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:dye_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:wither_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:blazing_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:nickel_bee" = 0.0
	#Range: 0.0 ~ 1.0
	"productivebees:skeletal_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:zinc_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:silver_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:zombie_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:ender_bee" = 0.85
	#Range: 0.0 ~ 1.0
	"productivebees:diamond_bee" = 0.05
	#Range: 0.0 ~ 1.0
	"productivebees:tin_bee" = 0.05
	#Spawn skeletal and zombie bees as night?
	spawnUndeadBees = true
	#Range: 0.0 ~ 1.0
	"productivebees:aluminium_bee" = 0.0
	#Range: 0.0 ~ 1.0
	"productivebees:platinum_bee" = 0.0
	#Range: 0.0 ~ 1.0
	"productivebees:quartz_bee" = 0.05

