
[item]

	[item.treasurebag]
		#If true, treasure bags will always spawn items on top of the player.
		#Otherwise this only happens if the player's inventory is full
		#Useful for bag-type items; Dank Storage, SGems Gem Bag, backpacks
		alwaysSpawnItems = true

